spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
